server:
  port: 8090

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source,paul
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?characterEncoding=UTF-8
    username: root
    password: GYh031125


#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          TRACE


#保持一致
dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qosPort: 11112
  protocol:
    name: dubbo
    port: 22220
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

